matrix:
  allow_failures:
    - env: GHCVER=head CABALVER=head

env:
 - GHCVER=7.8.4 CABALVER=1.20
 - GHCVER=7.10.1 CABALVER=1.22
 - GHCVER=head CABALVER=head

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER libicu-dev
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-$CABALVER update
 - travis_retry cabal-$CABALVER install Cabal
 - travis_retry cabal-$CABALVER install alex happy
 - travis_retry cabal-$CABALVER install gtk2hs-buildtools

script:
 - cabal-$CABALVER install

notifications:
  irc: "chat.freenode.net#yi"
